#!/usr/bin/env ruby

#######################
## Santiago Gonzalez ##
#######################

require_relative "simulation"

unless ARGV.length == 3
  puts "Usage: SIM N TIME SEED PEDARRIVAL AUTOARRIVAL PEDRATE AUTORATE TRACE"
  exit 1
end

Simulation.new ARGV[0][0], ARGV[1].to_i, ARGV[2].to_f, ARGV[7]

exit 0
